apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default "cloudflare-api-token" }}
  namespace: {{ .Values.namespace | default "cloudflare-ddns" }}
  labels:
    {{- include "cloudflare-ddns.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.key | default "api-token" }}: {{ .Values.cloudflareApiToken | b64enc }}